name: Correct Image Orientation
on:
  issue_comment:
    types: [created, edited]

jobs:
  cropimage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/images')
    steps:
      - name: Get PR info
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: "${{ github.event.issue.number}}" ,
            });
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: "${{ github.event.issue.number}}" ,
            });
            core.setOutput("ref", pr.data.head.ref);
            core.setOutput("base_sha", commits.data[0].parents[0].sha);
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.pr_info.outputs.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Python
        run: |
          pip install Pillow
          pip install opencv-contrib-python
          pip install opencv-python
      - name: Gather changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.jpg
            **.jpeg
            **.png
            **.tif
            **.tiff
          files_ignore: |
            **thumbnail**
          base_sha: "${{ steps.pr_info.outputs.base_sha }}"
      - name: Find Images With Wrong Orientation
        id: find-images
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: |
          $GITHUB_WORKSPACE/.github/scripts/checkImageOrientation.py $ALL_CHANGED_FILES >> $GITHUB_OUTPUT
      - name: Correct Image Orientation
        id: correct-image-orientation
        if: ${{ steps.find-images.outputs.wrong_sized_images != '' }}
        run: |
          echo "The following images are not in the correct orientation:"
          echo "${{ steps.find-images.outputs.wrong_sized_images }}"
          $GITHUB_WORKSPACE/.github/scripts/imageCrop.py ${{ steps.find-images.outputs.wrong_sized_images }}
      - name: Commit and Push Changes
        if: ${{ steps.find-images.outputs.wrong_sized_images != '' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ steps.find-images.outputs.wrong_sized_images }}
          git commit -m "[Bot]Correct image orientation"
          git push
          
